document.writeln("<div class=\'row\'>");
document.writeln("<div class=\'col-1-4\'>");
document.writeln("<div class=\'wrap-col\'>");
document.writeln("<div class=\'post\'>");
document.writeln("<div class=\'view effect\'> <img class=\'thumb\' src=\'/images/file/www/solution/mineral/58b1511d828e5beaa5b3da3f4befb593.jpg\'  />");
document.writeln("<div class=\'mask\'> <a href=\'/solutions/barite-processing-plant.html\' class=\'info\'><img src=\'/themes/zeroth/images/play_button_64.png\' /></a> </div>");
document.writeln("</div>");
document.writeln("<div class=\'clear\'></div>");
document.writeln("<a href=\'/solutions/barite-processing-plant.html\'>");
document.writeln("<h3>Barite processing plant</h3>");
document.writeln("</a> <span>Baryte, or barite, is a mineral consisti&hellip;</span> </div>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("<div class=\'col-1-4\'>");
document.writeln("<div class=\'wrap-col\'>");
document.writeln("<div class=\'post\'>");
document.writeln("<div class=\'view effect\'> <img class=\'thumb\' src=\'/images/file/www/solution/mineral/39124d989a052bb72760f856b002a3bc.jpg\'  />");
document.writeln("<div class=\'mask\'> <a href=\'/solutions/basalt-stone-processing-plant.html\' class=\'info\'><img src=\'/themes/zeroth/images/play_button_64.png\' /></a> </div>");
document.writeln("</div>");
document.writeln("<div class=\'clear\'></div>");
document.writeln("<a href=\'/solutions/basalt-stone-processing-plant.html\'>");
document.writeln("<h3>Basalt stone processing plant</h3>");
document.writeln("</a> <span>Basalt is the ideal materials to mix asp&hellip;</span> </div>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("<div class=\'col-1-4\'>");
document.writeln("<div class=\'wrap-col\'>");
document.writeln("<div class=\'post\'>");
document.writeln("<div class=\'view effect\'> <img class=\'thumb\' src=\'/images/file/www/solution/mineral/04d13cbedd53630d52e1e235fa6948b9.jpg\'  />");
document.writeln("<div class=\'mask\'> <a href=\'/solutions/bauxite-processing-plant.html\' class=\'info\'><img src=\'/themes/zeroth/images/play_button_64.png\' /></a> </div>");
document.writeln("</div>");
document.writeln("<div class=\'clear\'></div>");
document.writeln("<a href=\'/solutions/bauxite-processing-plant.html\'>");
document.writeln("<h3>Bauxite processing plant</h3>");
document.writeln("</a> <span>Bauxite mine is actually kind of ore min&hellip;</span> </div>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("<div class=\'col-1-4\'>");
document.writeln("<div class=\'wrap-col\'>");
document.writeln("<div class=\'post\'>");
document.writeln("<div class=\'view effect\'> <img class=\'thumb\' src=\'/images/file/www/solution/mineral/660ee1d09a1767c053728a722877deb7.jpg\'  />");
document.writeln("<div class=\'mask\'> <a href=\'/solutions/calcite-mining-and-processing-plant.html\' class=\'info\'><img src=\'/themes/zeroth/images/play_button_64.png\' /></a> </div>");
document.writeln("</div>");
document.writeln("<div class=\'clear\'></div>");
document.writeln("<a href=\'/solutions/calcite-mining-and-processing-plant.html\'>");
document.writeln("<h3>Calcite mining and processing plant</h3>");
document.writeln("</a> <span>GULIN Machinery is professional manufact&hellip;</span> </div>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("<div class=\'row\'>");
document.writeln("<div class=\'col-1-4\'>");
document.writeln("<div class=\'wrap-col\'>");
document.writeln("<div class=\'post\'>");
document.writeln("<div class=\'view effect\'> <img class=\'thumb\' src=\'/images/file/www/solution/mineral/737ffeac272d9a7400c7e3509daa7387.jpg\'  />");
document.writeln("<div class=\'mask\'> <a href=\'/solutions/copper-ore-beneficiation-plant.html\' class=\'info\'><img src=\'/themes/zeroth/images/play_button_64.png\' /></a> </div>");
document.writeln("</div>");
document.writeln("<div class=\'clear\'></div>");
document.writeln("<a href=\'/solutions/copper-ore-beneficiation-plant.html\'>");
document.writeln("<h3>Copper ore beneficiation plant</h3>");
document.writeln("</a> <span>Copper ore a valuable mineral source for&hellip;</span> </div>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("<div class=\'col-1-4\'>");
document.writeln("<div class=\'wrap-col\'>");
document.writeln("<div class=\'post\'>");
document.writeln("<div class=\'view effect\'> <img class=\'thumb\' src=\'/images/file/www/solution/mineral/9e1924cafbffd1fe93b021852becdc61.jpg\'  />");
document.writeln("<div class=\'mask\'> <a href=\'/solutions/dolomite-stone-processing-plant.html\' class=\'info\'><img src=\'/themes/zeroth/images/play_button_64.png\' /></a> </div>");
document.writeln("</div>");
document.writeln("<div class=\'clear\'></div>");
document.writeln("<a href=\'/solutions/dolomite-stone-processing-plant.html\'>");
document.writeln("<h3>Dolomite stone processing plant</h3>");
document.writeln("</a> <span>Dolomite is kind of carbonate mineral wh&hellip;</span> </div>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("<div class=\'col-1-4\'>");
document.writeln("<div class=\'wrap-col\'>");
document.writeln("<div class=\'post\'>");
document.writeln("<div class=\'view effect\'> <img class=\'thumb\' src=\'/images/file/www/solution/mineral/0526da3a73be461cd521099d7ca371d8.jpg\'  />");
document.writeln("<div class=\'mask\'> <a href=\'/solutions/feldspar-processing-plant.html\' class=\'info\'><img src=\'/themes/zeroth/images/play_button_64.png\' /></a> </div>");
document.writeln("</div>");
document.writeln("<div class=\'clear\'></div>");
document.writeln("<a href=\'/solutions/feldspar-processing-plant.html\'>");
document.writeln("<h3>Feldspar processing plant</h3>");
document.writeln("</a> <span>Feldspar is the most common ore in the e&hellip;</span> </div>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("<div class=\'col-1-4\'>");
document.writeln("<div class=\'wrap-col\'>");
document.writeln("<div class=\'post\'>");
document.writeln("<div class=\'view effect\'> <img class=\'thumb\' src=\'/images/file/www/solution/mineral/ed401c66864701a315045d21c4e296e4.jpg\'  />");
document.writeln("<div class=\'mask\'> <a href=\'/solutions/feldspar-stone-processing-plant.html\' class=\'info\'><img src=\'/themes/zeroth/images/play_button_64.png\' /></a> </div>");
document.writeln("</div>");
document.writeln("<div class=\'clear\'></div>");
document.writeln("<a href=\'/solutions/feldspar-stone-processing-plant.html\'>");
document.writeln("<h3>Feldspar stone processing plant</h3>");
document.writeln("</a> <span>Feldspar is the most common ore in the e&hellip;</span> </div>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("<div class=\'row\'>");
document.writeln("<div class=\'col-1-4\'>");
document.writeln("<div class=\'wrap-col\'>");
document.writeln("<div class=\'post\'>");
document.writeln("<div class=\'view effect\'> <img class=\'thumb\' src=\'/images/file/www/solution/mineral/f804216505c393ad2ff6d7c1a22eaffb.jpg\'  />");
document.writeln("<div class=\'mask\'> <a href=\'/solutions/kaolin-processing-plant.html\' class=\'info\'><img src=\'/themes/zeroth/images/play_button_64.png\' /></a> </div>");
document.writeln("</div>");
document.writeln("<div class=\'clear\'></div>");
document.writeln("<a href=\'/solutions/kaolin-processing-plant.html\'>");
document.writeln("<h3>Kaolin processing plant</h3>");
document.writeln("</a> <span>Kaolin is one of the most common mineral&hellip;</span> </div>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("<div class=\'col-1-4\'>");
document.writeln("<div class=\'wrap-col\'>");
document.writeln("<div class=\'post\'>");
document.writeln("<div class=\'view effect\'> <img class=\'thumb\' src=\'/images/file/www/solution/mineral/908c9851d64e9b6a24ea5606ac6b8df6.jpg\'  />");
document.writeln("<div class=\'mask\'> <a href=\'/solutions/limestone-crushing-plant.html\' class=\'info\'><img src=\'/themes/zeroth/images/play_button_64.png\' /></a> </div>");
document.writeln("</div>");
document.writeln("<div class=\'clear\'></div>");
document.writeln("<a href=\'/solutions/limestone-crushing-plant.html\'>");
document.writeln("<h3>Limestone crushing plant</h3>");
document.writeln("</a> <span>Limestone is a common nonmetallic minera&hellip;</span> </div>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("<div class=\'col-1-4\'>");
document.writeln("<div class=\'wrap-col\'>");
document.writeln("<div class=\'post\'>");
document.writeln("<div class=\'view effect\'> <img class=\'thumb\' src=\'/images/file/www/solution/mineral/908c9851d64e9b6a24ea5606ac6b8df6.jpg\'  />");
document.writeln("<div class=\'mask\'> <a href=\'/solutions/limestone-processing-plant.html\' class=\'info\'><img src=\'/themes/zeroth/images/play_button_64.png\' /></a> </div>");
document.writeln("</div>");
document.writeln("<div class=\'clear\'></div>");
document.writeln("<a href=\'/solutions/limestone-processing-plant.html\'>");
document.writeln("<h3>Limestone Processing Plant</h3>");
document.writeln("</a> <span>Limestone is a common nonmetallic minera&hellip;</span> </div>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("<div class=\'col-1-4\'>");
document.writeln("<div class=\'wrap-col\'>");
document.writeln("<div class=\'post\'>");
document.writeln("<div class=\'view effect\'> <img class=\'thumb\' src=\'/images/file/www/solution/mineral/68c4353c30b3bb87e7568b595cd1a7da.jpg\'  />");
document.writeln("<div class=\'mask\'> <a href=\'/solutions/manganese-processing-plant.html\' class=\'info\'><img src=\'/themes/zeroth/images/play_button_64.png\' /></a> </div>");
document.writeln("</div>");
document.writeln("<div class=\'clear\'></div>");
document.writeln("<a href=\'/solutions/manganese-processing-plant.html\'>");
document.writeln("<h3>Manganese processing plant</h3>");
document.writeln("</a> <span>Manganese is essential to iron and steel&hellip;</span> </div>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("</div>");